#!/usr/bin/env python3
# -*- coding:UTF-8 -*-
# Copyright (c) Météo France (2014-)
# This software is governed by the CeCILL-C license under French law.
# http://www.cecill.info

# Coordinates 
coordinates = {
  'time' : {'standard_name':'time'                 , 'units': 'seconds since YYYY-MM-DD HH:MM:SS'},
  'time_budget' : {'standard_name':'time_budget'   , 'units': 'seconds since YYYY-MM-DD HH:MM:SS'},
  'levf' : {'standard_name':'full_level_coordinate', 'units':                                 '1'},
  'levh' : {'standard_name':'half_level_coordinate', 'units':                                 '1'},
  'plev' : {'standard_name':'air_pressure'         , 'units':                                'Pa'},
}

# Variables
variables = {
# 1. Standard variables
  'longitude' : {'standard_name':'longitude'                          , 'units':'degrees_east'} ,
  'latitude'  : {'standard_name':'latitude'                           , 'units':'degrees_north'},
  'pa'        : {'standard_name':'air_pressure'                       , 'units':'Pa'}           ,
  'pfull'     : {'standard_name':'air_pressure_on_model_levels'       , 'units':'Pa'}           ,
  'phalf'     : {'standard_name':'air_pressure_on_model_half_levels'  , 'units':'Pa'}           ,
  'zg'        : {'standard_name':'height'                             , 'units':'m'}            ,
  'zfull'     : {'standard_name':'height_of_model_levels'             , 'units':'m'}            ,
  'zhalf'     : {'standard_name':'height_of_model_half_levels'        , 'units':'m'}            ,
  'rho'       : {'standard_name':'air_volumic_mass'                   , 'units':'kg m-3'}       ,
  'ta'        : {'standard_name':'air_temperature'                    , 'units':'K'}            ,
  'qv'        : {'standard_name':'specific_humidity'                  , 'units':'1'}            ,
  'rv'        : {'standard_name':'humidity_mixing_ratio'              , 'units':'1'}            ,
  'qt'        : {'standard_name':'total_water_content'                , 'units':'1'}            ,
  'rt'        : {'standard_name':'total_water_mixing_ratio'           , 'units':'1'}            ,
  'hur'       : {'standard_name':'relative_humidity'                  , 'units':'1'}            ,
  'hurl'      : {'standard_name':'relative_humidity_wrt_liquid'       , 'units':'1'}            ,
  'huri'      : {'standard_name':'relative_humidity_wrt_ice'          , 'units':'1'}            ,
  'ua'        : {'standard_name':'eastward_wind'                      , 'units':'m s-1'}        ,
  'va'        : {'standard_name':'northward_wind'                     , 'units':'m s-1'}        ,
  'windspeed' : {'standard_name':'horizontal_wind_speed'              , 'units':'m s-1'}        ,
  'wa'        : {'standard_name':'upward_air_velocity'                , 'units':'m s-1'}        ,
  'wap'       : {'standard_name':'lagrangian_tendency_of_air_pressure', 'units':'Pa s-1'}       ,
  'theta'     : {'standard_name':'air_potential_temperature'          , 'units':'K'}            ,
  'thetav'    : {'standard_name':'air_virtual_potential_temperature'  , 'units':'K'}            ,
  'thetal'    : {'standard_name':'air_liquid_potential_temperature'   , 'units':'K'}            ,
  'tke'       : {'standard_name':'specific_turbulent_kinetic_energy'  , 'units':'m2 s-2'}       ,

# 2. Microphysical species
  'qlrad' : {'standard_name':'radiatively_active_liquid_water_content'              , 'units':'1'},
  'qirad' : {'standard_name':'radiatively_active_ice_water_content'                 , 'units':'1'},
  'ql'    : {'standard_name':'mass_fraction_of_cloud_liquid_water_in_air'           , 'units':'1'},
  'qls'   : {'standard_name':'mass_fraction_of_stratiform_cloud_liquid_water_in_air', 'units':'1'},
  'qlc'   : {'standard_name':'mass_fraction_of_convective_cloud_liquid_water_in_air', 'units':'1'},
  'qi'    : {'standard_name':'mass_fraction_of_cloud_ice_water_in_air'              , 'units':'1'},
  'qis'   : {'standard_name':'mass_fraction_of_stratiform_cloud_ice_water_in_air'   , 'units':'1'},
  'qic'   : {'standard_name':'mass_fraction_of_convective_cloud_ice_water_in_air'   , 'units':'1'},
  'qr'    : {'standard_name':'mass_fraction_of_rain_water_in_air'                   , 'units':'1'},
  'qrs'   : {'standard_name':'mass_fraction_of_stratiform_rain_water_in_air'        , 'units':'1'},
  'qrc'   : {'standard_name':'mass_fraction_of_convective_rain_water_in_air'        , 'units':'1'},
  'qsn'   : {'standard_name':'mass_fraction_of_snow_water_in_air'                   , 'units':'1'},
  'qsns'  : {'standard_name':'mass_fraction_of_stratiform_snow_water_in_air'        , 'units':'1'},
  'qsnc'  : {'standard_name':'mass_fraction_of_convective_snow_water_in_air'        , 'units':'1'},
  'rl'    : {'standard_name':'cloud_liquid_water_mixing_ratio'                      , 'units':'1'},
  'ri'    : {'standard_name':'cloud_ice_water_mixing_ratio'                         , 'units':'1'},
  'rr'    : {'standard_name':'rain_water_mixing_ratio'                              , 'units':'1'},
  'rsn'   : {'standard_name':'snow_water_mixing_ratio'                              , 'units':'1'},

# 3. Cloud variables
  'cl'  : {'standard_name':'cloud_area_fraction_in_atmospheric_layer'           , 'units':'1'},
  'cls' : {'standard_name':'stratiform_cloud_area_fraction_in_atmospheric_layer', 'units':'1'},
  'clc' : {'standard_name':'convective_cloud_area_fraction_in_atmospheric_layer', 'units':'1'},
  'clt' : {'standard_name':'cloud_area_fraction'                                , 'units':'1'},

# 4. Precipitation variables
  'pr'   : {'standard_name':'precipitation_flux_at_surface', 'units':'kg m-2 s-1'},
  'prl'  : {'standard_name':'rainfall_flux_at_surface'     , 'units':'kg m-2 s-1'},
  'prsn' : {'standard_name':'snowfall_flux_at_surface'     , 'units':'kg m-2 s-1'},

# 5. Vertically-integrated variables
  'prw'     : {'standard_name':'atmospheric_water_vapor_path'                          , 'units':'kg m-2'},
  'cwp_rad' : {'standard_name':'atmospheric_condensed_water_path_relevant_to_radiation', 'units':'kg m-2'},
  'lwp_rad' : {'standard_name':'atmospheric_liquid_water_path_relevant_to_radiation'   , 'units':'kg m-2'},
  'iwp_rad' : {'standard_name':'atmospheric_ice_water_path_relevant_to_radiation'      , 'units':'kg m-2'},
  'cwp'     : {'standard_name':'atmospheric_condensed_water_path'                      , 'units':'kg m-2'},
  'lwp'     : {'standard_name':'atmospheric_liquid_water_path'                         , 'units':'kg m-2'},
  'iwp'     : {'standard_name':'atmospheric_ice_water_path'                            , 'units':'kg m-2'},
  'rwp'     : {'standard_name':'atmospheric_rain_water_path'                           , 'units':'kg m-2'},
  'swp'     : {'standard_name':'atmospheric_snow_water_path'                           , 'units':'kg m-2'},
  'gwp'     : {'standard_name':'atmospheric_graupel_water_path'                        , 'units':'kg m-2'},

# 6. Surface turbulent flux variables
  'hfss'  : {'standard_name':'surface_upward_sensible_heat_flux', 'units':'W m-2'},
  'hfls'  : {'standard_name':'surface_upward_latent_heat_flux'  , 'units':'W m-2'},
  'ustar' : {'standard_name':'surface_friction_velocity'        , 'units':'m s-1'},

# 7. Surface variables
  'ps'    : {'standard_name':'surface_pressure'        , 'units':'Pa'}    ,
  'ts'    : {'standard_name':'surface_temperature'     , 'units':'K'}     ,
  'tskin' : {'standard_name':'skin_surface_temperature', 'units':'K'}     ,
  'tas'   : {'standard_name':'2m_air_temperature'      , 'units':'K'}     ,
  'qvs'   : {'standard_name':'2m_specific_humidity'    , 'units':'1'}     ,
  'qs'    : {'standard_name':'surface_humidity'        , 'units':'1'}     ,
  'mrso'  : {'standard_name':'soil_moisture_content'   , 'units':'kg m-2'},

# 8. Tendencies
  'tnta'         : {'standard_name':'tendency_of_air_temperature'                              , 'units':'K s-1'},
  'tnta_adv'     : {'standard_name':'tendency_of_air_temperature_due_to_advection'             , 'units':'K s-1'},
  'tnta_advh'    : {'standard_name':'tendency_of_air_temperature_due_to_horizontal_advection'  , 'units':'K s-1'},
  'tnta_advv'    : {'standard_name':'tendency_of_air_temperature_due_to_vertical_advection'    , 'units':'K s-1'},
  'tnta_nud'     : {'standard_name':'tendency_of_air_temperature_due_to_nudging'               , 'units':'K s-1'},
  'tnta_diab'    : {'standard_name':'tendency_of_air_temperature_due_to_diabatic_processes'    , 'units':'K s-1'},
  'tnta_conv'    : {'standard_name':'tendency_of_air_temperature_due_to_convection'            , 'units':'K s-1'},
  'tnta_shconv'  : {'standard_name':'tendency_of_air_temperature_due_to_shallow_convection'    , 'units':'K s-1'},
  'tnta_dconv'   : {'standard_name':'tendency_of_air_temperature_due_to_deep_convection'       , 'units':'K s-1'},
  'tnta_turb'    : {'standard_name':'tendency_of_air_temperature_due_to_turbulence'            , 'units':'K s-1'},
  'tnta_micro'   : {'standard_name':'tendency_of_air_temperature_due_to_microphysics'          , 'units':'K s-1'},
  'tnta_rad'     : {'standard_name':'tendency_of_air_temperature_due_to_radiation'             , 'units':'K s-1'},
  'tnta_radsw'   : {'standard_name':'tendency_of_air_temperature_due_to_sw_radiation'          , 'units':'K s-1'},
  'tnta_radlw'   : {'standard_name':'tendency_of_air_temperature_due_to_lw_radiation'          , 'units':'K s-1'},
  'tnta_radswcs' : {'standard_name':'tendency_of_air_temperature_due_to_sw_clear_sky_radiation', 'units':'K s-1'},
  'tnta_radlwcs' : {'standard_name':'tendency_of_air_temperature_due_to_lw_clear_sky_radiation', 'units':'K s-1'},
  'tnta_wake'    : {'standard_name':'tendency_of_air_temperature_due_to_wake'                  , 'units':'K s-1'},
  'tntheta'      : {'standard_name':'tendency_of_air_temperature'                              , 'units':'K s-1'},
  'tntheta_adv'     : {'standard_name':'tendency_of_air_potential_temperature_due_to_advection'             , 'units':'K s-1'},
  'tntheta_advh'    : {'standard_name':'tendency_of_air_potential_temperature_due_to_horizontal_advection'  , 'units':'K s-1'},
  'tntheta_advv'    : {'standard_name':'tendency_of_air_potential_temperature_due_to_vertical_advection'    , 'units':'K s-1'},
  'tntheta_nud'     : {'standard_name':'tendency_of_air_potential_temperature_due_to_nudging'               , 'units':'K s-1'},
  'tntheta_diab'    : {'standard_name':'tendency_of_air_potential_temperature_due_to_diabatic_processes'    , 'units':'K s-1'},
  'tntheta_conv'    : {'standard_name':'tendency_of_air_potential_temperature_due_to_convection'            , 'units':'K s-1'},
  'tntheta_shconv'  : {'standard_name':'tendency_of_air_potential_temperature_due_to_shallow_convection'    , 'units':'K s-1'},
  'tntheta_dconv'   : {'standard_name':'tendency_of_air_potential_temperature_due_to_deep_convection'       , 'units':'K s-1'},
  'tntheta_turb'    : {'standard_name':'tendency_of_air_potential_temperature_due_to_turbulence'            , 'units':'K s-1'},
  'tntheta_micro'   : {'standard_name':'tendency_of_air_potential_temperature_due_to_microphysics'          , 'units':'K s-1'},
  'tntheta_rad'     : {'standard_name':'tendency_of_air_potential_temperature_due_to_radiation'             , 'units':'K s-1'},
  'tntheta_radsw'   : {'standard_name':'tendency_of_air_potential_temperature_due_to_sw_radiation'          , 'units':'K s-1'},
  'tntheta_radlw'   : {'standard_name':'tendency_of_air_potential_temperature_due_to_lw_radiation'          , 'units':'K s-1'},
  'tntheta_radswcs' : {'standard_name':'tendency_of_air_potential_temperature_due_to_sw_clear_sky_radiation', 'units':'K s-1'},
  'tntheta_radlwcs' : {'standard_name':'tendency_of_air_potential_temperature_due_to_lw_clear_sky_radiation', 'units':'K s-1'},
  'tntheta_wake'    : {'standard_name':'tendency_of_air_potential_temperature_due_to_wake'                  , 'units':'K s-1'},
  'tnqv'         : {'standard_name':'tendency_of_specific_humidity'                            , 'units':'s-1'}  ,
  'tnqv_adv'     : {'standard_name':'tendency_of_specific_humidity_due_to_advection'           , 'units':'s-1'}  ,
  'tnqv_advh'    : {'standard_name':'tendency_of_specific_humidity_due_to_horizontal_advection', 'units':'s-1'}  ,
  'tnqv_advv'    : {'standard_name':'tendency_of_specific_humidity_due_to_vertical_advection'  , 'units':'s-1'}  ,
  'tnqv_nud'     : {'standard_name':'tendency_of_specific_humidity_due_to_nudging'             , 'units':'s-1'}  ,
  'tnqv_diab'    : {'standard_name':'tendency_of_specific_humidity_due_to_diabatic_processes'  , 'units':'s-1'}  ,
  'tnqv_conv'    : {'standard_name':'tendency_of_specific_humidity_due_to_convection'          , 'units':'s-1'}  ,
  'tnqv_shconv'  : {'standard_name':'tendency_of_specific_humidity_due_to_shallow_convection'  , 'units':'s-1'}  ,
  'tnqv_dconv'   : {'standard_name':'tendency_of_specific_humidity_due_to_deep_convection'     , 'units':'s-1'}  ,
  'tnqv_turb'    : {'standard_name':'tendency_of_specific_humidity_due_to_turbulence'          , 'units':'s-1'}  ,
  'tnqv_micro'   : {'standard_name':'tendency_of_specific_humidity_due_to_microphysics'        , 'units':'s-1'}  ,
  'tnqv_wake'    : {'standard_name':'tendency_of_specific_humidity_due_to_wake'                , 'units':'s-1'}  ,
  'tnrv'         : {'standard_name':'tendency_of_humidity_mixing_ratio'                            , 'units':'s-1'}  ,
  'tnrv_adv'     : {'standard_name':'tendency_of_humidity_mixing_ratio_due_to_advection'           , 'units':'s-1'}  ,
  'tnrv_advh'    : {'standard_name':'tendency_of_humidity_mixing_ratio_due_to_horizontal_advection', 'units':'s-1'}  ,
  'tnrv_advv'    : {'standard_name':'tendency_of_humidity_mixing_ratio_due_to_vertical_advection'  , 'units':'s-1'}  ,
  'tnrv_nud'     : {'standard_name':'tendency_of_humidity_mixing_ratio_due_to_nudging'             , 'units':'s-1'}  ,
  'tnrv_diab'    : {'standard_name':'tendency_of_humidity_mixing_ratio_due_to_diabatic_processes'  , 'units':'s-1'}  ,
  'tnrv_conv'    : {'standard_name':'tendency_of_humidity_mixing_ratio_due_to_convection'          , 'units':'s-1'}  ,
  'tnrv_shconv'  : {'standard_name':'tendency_of_humidity_mixing_ratio_due_to_shallow_convection'  , 'units':'s-1'}  ,
  'tnrv_dconv'   : {'standard_name':'tendency_of_humidity_mixing_ratio_due_to_deep_convection'     , 'units':'s-1'}  ,
  'tnrv_turb'    : {'standard_name':'tendency_of_humidity_mixing_ratio_due_to_turbulence'          , 'units':'s-1'}  ,
  'tnrv_micro'   : {'standard_name':'tendency_of_humidity_mixing_ratio_due_to_microphysics'        , 'units':'s-1'}  ,
  'tnrv_wake'    : {'standard_name':'tendency_of_humidity_mixing_ratio_due_to_wake'                , 'units':'s-1'}  ,
  'tnrl'         : {'standard_name':'tendency_of_cloud_liquid_water_mixing_ratio'                            , 'units':'s-1'}  ,
  'tnrl_adv'     : {'standard_name':'tendency_of_cloud_liquid_water_mixing_ratio_due_to_advection'           , 'units':'s-1'}  ,
  'tnrl_advh'    : {'standard_name':'tendency_of_cloud_liquid_water_mixing_ratio_due_to_horizontal_advection', 'units':'s-1'}  ,
  'tnrl_advv'    : {'standard_name':'tendency_of_cloud_liquid_water_mixing_ratio_due_to_vertical_advection'  , 'units':'s-1'}  ,
  'tnrl_nud'     : {'standard_name':'tendency_of_cloud_liquid_water_mixing_ratio_due_to_nudging'             , 'units':'s-1'}  ,
  'tnrl_diab'    : {'standard_name':'tendency_of_cloud_liquid_water_mixing_ratio_due_to_diabatic_processes'  , 'units':'s-1'}  ,
  'tnrl_conv'    : {'standard_name':'tendency_of_cloud_liquid_water_mixing_ratio_due_to_convection'          , 'units':'s-1'}  ,
  'tnrl_shconv'  : {'standard_name':'tendency_of_cloud_liquid_water_mixing_ratio_due_to_shallow_convection'  , 'units':'s-1'}  ,
  'tnrl_dconv'   : {'standard_name':'tendency_of_cloud_liquid_water_mixing_ratio_due_to_deep_convection'     , 'units':'s-1'}  ,
  'tnrl_turb'    : {'standard_name':'tendency_of_cloud_liquid_water_mixing_ratio_due_to_turbulence'          , 'units':'s-1'}  ,
  'tnrl_micro'   : {'standard_name':'tendency_of_cloud_liquid_water_mixing_ratio_due_to_microphysics'        , 'units':'s-1'}  ,
  'tnrl_wake'    : {'standard_name':'tendency_of_cloud_liquid_water_mixing_ratio_due_to_wake'                , 'units':'s-1'}  ,
  'tnua'         : {'standard_name':'tendency_of_eastward_wind'                                , 'units':'m s-2'},
  'tnua_adv'     : {'standard_name':'tendency_of_eastward_wind_due_to_advection'               , 'units':'m s-2'},
  'tnua_advh'    : {'standard_name':'tendency_of_eastward_wind_due_to_horizontal_advection'    , 'units':'m s-2'},
  'tnua_advv'    : {'standard_name':'tendency_of_eastward_wind_due_to_vertical_advection'      , 'units':'m s-2'},
  'tnua_nud'     : {'standard_name':'tendency_of_eastward_wind_due_to_nudging'                 , 'units':'m s-2'},
  'tnua_geo'     : {'standard_name':'tendency_of_eastward_wind_due_to_geostrophic_forcing'     , 'units':'m s-2'},
  'tnua_diab'    : {'standard_name':'tendency_of_eastward_wind_due_to_diabatic_processes'      , 'units':'m s-2'},
  'tnua_conv'    : {'standard_name':'tendency_of_eastward_wind_due_to_convection'              , 'units':'m s-2'},
  'tnua_shconv'  : {'standard_name':'tendency_of_eastward_wind_due_to_shallow_convection'      , 'units':'m s-2'},
  'tnua_dconv'   : {'standard_name':'tendency_of_eastward_wind_due_to_deep_convection'         , 'units':'m s-2'},
  'tnua_turb'    : {'standard_name':'tendency_of_eastward_wind_due_to_turbulence'              , 'units':'m s-2'},
  'tnva'         : {'standard_name':'tendency_of_northward_wind'                               , 'units':'m s-2'},
  'tnva_adv'     : {'standard_name':'tendency_of_northward_wind_due_to_advection'              , 'units':'m s-2'},
  'tnva_advh'    : {'standard_name':'tendency_of_northward_wind_due_to_horizontal_advection'   , 'units':'m s-2'},
  'tnva_advv'    : {'standard_name':'tendency_of_northward_wind_due_to_vertical_advection'     , 'units':'m s-2'},
  'tnva_nud'     : {'standard_name':'tendency_of_northward_wind_due_to_nudging'                , 'units':'m s-2'},
  'tnva_geo'     : {'standard_name':'tendency_of_northward_wind_due_to_geostrophic_forcing'    , 'units':'m s-2'},
  'tnva_diab'    : {'standard_name':'tendency_of_northward_wind_due_to_diabatic_processes'     , 'units':'m s-2'},
  'tnva_conv'    : {'standard_name':'tendency_of_northward_wind_due_to_convection'             , 'units':'m s-2'},
  'tnva_shconv'  : {'standard_name':'tendency_of_northward_wind_due_to_shallow_convection'     , 'units':'m s-2'},
  'tnva_dconv'   : {'standard_name':'tendency_of_northward_wind_due_to_deep_convection'        , 'units':'m s-2'},
  'tnva_turb'    : {'standard_name':'tendency_of_northward_wind_due_to_turbulence'             , 'units':'m s-2'},

# 9. Fluxes : To be completed ...

# 10. Convection parameterization variables
  'mf_up'           : {'standard_name':'convective_updraft_mass_flux'                                         , 'units':'kg m-2 s-1'},
  'alpha_up'        : {'standard_name':'convective_updraft_fraction'                                          , 'units':'1'}         ,
  'wa_up'           : {'standard_name':'convective_updraft_upward_velocity'                                   , 'units':'m s-1'}     ,
  'wap_up'          : {'standard_name':'convective_updraft_lagrangian_tendency_of_air_pressure'               , 'units':'Pa s-1'}    ,
  'ta_up'           : {'standard_name':'convective_updraft_air_temperature'                                   , 'units':'K'}         ,
  'theta_up'        : {'standard_name':'convective_updraft_air_potential_temperature'                         , 'units':'K'}         ,
  'thetav_up'       : {'standard_name':'convective_updraft_air_virtual_potential_temperature'                 , 'units':'K'}         ,
  'thetal_up'       : {'standard_name':'convective_updraft_air_liquid_potential_temperature'                  , 'units':'K'}         ,
  'qt_up'           : {'standard_name':'convective_updraft_total_water_content'                               , 'units':'1'}         ,
  'qv_up'           : {'standard_name':'convective_updraft_specific_humidity'                                 , 'units':'1'}         ,
  'ql_up'           : {'standard_name':'convective_updraft_mass_fraction_of_cloud_liquid_water_in_air'        ,'units':'1'}          ,
  'qi_up'           : {'standard_name':'convective_updraft_mass_fraction_of_cloud_ice_water_in_air'           , 'units':'1'}         ,
  'qr_up'           : {'standard_name':'convective_updraft_mass_fraction_of_rain_water_in_air'                , 'units':'1'}         ,
  'qsn_up'          : {'standard_name':'convective_updraft_mass_fraction_of_snow_water_in_air'                , 'units':'1'}         ,
  'rt_up'           : {'standard_name':'convective_updraft_total_water_mixing_ratio'                          , 'units':'1'}         ,
  'rv_up'           : {'standard_name':'convective_updraft_humidity_mixing_ratio'                             , 'units':'1'}         ,
  'rl_up'           : {'standard_name':'convective_updraft_cloud_liquid_water_mixing_ratio'                   , 'units':'1'}         ,
  'ri_up'           : {'standard_name':'convective_updraft_cloud_ice_water_mixing_ratio'                      , 'units':'1'}         ,
  'rr_up'           : {'standard_name':'convective_updraft_rain_water_mixing_ratio'                           , 'units':'1'}         ,
  'rsn_up'          : {'standard_name':'convective_updraft_snow_water_mixing_ratio'                           , 'units':'1'}         ,
  'b_up'            : {'standard_name':'convective_updraft_buoyancy'                                          , 'units':'m s-2'}     ,
  'ent_up'          : {'standard_name':'convective_updraft_fractional_entrainment'                            , 'units':'m-1'}       ,
  'det_up'          : {'standard_name':'convective_updraft_fractional_detrainment'                            , 'units':'m-1'}       ,
  'mf_up_shconv'    : {'standard_name':'shallow_convection_updraft_mass_flux'                                 , 'units':'kg m-2 s-1'},
  'alpha_up_shconv' : {'standard_name':'shallow_convective_updraft_fraction'                                  , 'units':'1'}         ,
  'wa_up_shconv'    : {'standard_name':'shallow_convective_updraft_vertical_velocity'                         , 'units':'m s-1'}     ,
  'wap_up_shconv'   : {'standard_name':'shallow_convective_updraft_pressure_velocity'                         , 'units':'Pa s-1'}    ,
  'ta_up_shconv'    : {'standard_name':'shallow_convective_updraft_temperature'                               , 'units':'K'}         ,
  'theta_up_shconv' : {'standard_name':'shallow_convective_updraft_air_potential_temperature'                 , 'units':'K'}         ,
  'thetav_up_shconv': {'standard_name':'shallow_convective_updraft_air_virtual_potential_temperature'         , 'units':'K'}         ,
  'thetal_up_shconv': {'standard_name':'shallow_convective_updraft_air_liquid_potential_temperature'          , 'units':'K'}         ,
  'qt_up_shconv'    : {'standard_name':'shallow_convective_updraft_total_water_content'                       , 'units':'1'}         ,
  'qv_up_shconv'    : {'standard_name':'shallow_convective_updraft_specific_humidity'                         , 'units':'1'}         ,
  'ql_up_shconv'    : {'standard_name':'shallow_convective_updraft_mass_fraction_of_cloud_liquid_water_in_air','units':'1'}          ,
  'qi_up_shconv'    : {'standard_name':'shallow_convective_updraft_mass_fraction_of_cloud_ice_water_in_air'   , 'units':'1'}         ,
  'qr_up_shconv'    : {'standard_name':'shallow_convective_updraft_mass_fraction_of_rain_water_in_air'        , 'units':'1'}         ,
  'qsn_up_shconv'   : {'standard_name':'shallow_convective_updraft_mass_fraction_of_snow_water_in_air'        , 'units':'1'}         ,
  'rt_up_shconv'    : {'standard_name':'shallow_convective_updraft_total_water_mixing_ratio'                  , 'units':'1'}         ,
  'rv_up_shconv'    : {'standard_name':'shallow_convective_updraft_humidity_mixing_ratio'                     , 'units':'1'}         ,
  'rl_up_shconv'    : {'standard_name':'shallow_convective_updraft_cloud_liquid_water_mixing_ratio'           , 'units':'1'}         ,
  'ri_up_shconv'    : {'standard_name':'shallow_convective_updraft_cloud_ice_water_mixing_ratio'              , 'units':'1'}         ,
  'rr_up_shconv'    : {'standard_name':'shallow_convective_updraft_rain_water_mixing_ratio'                   , 'units':'1'}         ,
  'rsn_up_shconv'   : {'standard_name':'shallow_convective_updraft_snow_water_mixing_ratio'                   , 'units':'1'}         ,
  'b_up_shconv'     : {'standard_name':'shallow_convective_updraft_buoyancy'                                  , 'units':'m s-2'}     ,
  'ent_up_shconv'   : {'standard_name':'shallow_convective_entrainment'                                       , 'units':'m-1'}       ,
  'det_up_shconv'   : {'standard_name':'shallow_convective_detrainment'                                       , 'units':'m-1'}       ,
  'mf_up_dconv'     : {'standard_name':'deep_convection_updraft_mass_flux'                                    , 'units':'kg m-2 s-1'},
  'alpha_up_dconv'  : {'standard_name':'deep_convective_updraft_fraction'                                     , 'units':'1'}         ,
  'wa_up_dconv'     : {'standard_name':'deep_convective_updraft_vertical_velocity'                            , 'units':'m s-1'}     ,
  'wap_up_dconv'    : {'standard_name':'deep_convective_updraft_pressure_velocity'                            , 'units':'Pa s-1'}    ,
  'ta_up_dconv'     : {'standard_name':'deep_convective_updraft_temperature'                                  , 'units':'K'}         ,
  'theta_up_dconv'  : {'standard_name':'deep_convective_updraft_air_potential_temperature'                    , 'units':'K'}         ,
  'thetav_up_dconv' : {'standard_name':'deep_convective_updraft_air_virtual_potential_temperature'            , 'units':'K'}         ,
  'thetal_up_dconv' : {'standard_name':'deep_convective_updraft_air_liquid_potential_temperature'             , 'units':'K'}         ,
  'qt_up_dconv'     : {'standard_name':'deep_convective_updraft_total_water_content'                          , 'units':'1'}         ,
  'qv_up_dconv'     : {'standard_name':'deep_convective_updraft_specific_humidity'                            , 'units':'1'}         ,
  'ql_up_dconv'     : {'standard_name':'deep_convective_updraft_mass_fraction_of_cloud_liquid_water_in_air'   , 'units':'1'}         ,
  'qi_up_dconv'     : {'standard_name':'deep_convective_updraft_mass_fraction_of_cloud_ice_water_in_air'      , 'units':'1'}         ,
  'qr_up_dconv'     : {'standard_name':'deep_convective_updraft_mass_fraction_of_rain_water_in_air'           , 'units':'1'}         ,
  'qsn_up_dconv'    : {'standard_name':'deep_convective_updraft_mass_fraction_of_snow_water_in_air'           , 'units':'1'}         ,
  'rt_up_dconv'     : {'standard_name':'deep_convective_updraft_total_water_mixing_ratio'                     , 'units':'1'}         ,
  'rv_up_dconv'     : {'standard_name':'deep_convective_updraft_humidity_mixing_ratio'                        , 'units':'1'}         ,
  'rl_up_dconv'     : {'standard_name':'deep_convective_updraft_cloud_liquid_water_mixing_ratio'              , 'units':'1'}         ,
  'ri_up_dconv'     : {'standard_name':'deep_convective_updraft_cloud_ice_water_mixing_ratio'                 , 'units':'1'}         ,
  'rr_up_dconv'     : {'standard_name':'deep_convective_updraft_rain_water_mixing_ratio'                      , 'units':'1'}         ,
  'rsn_up_dconv'    : {'standard_name':'deep_convective_updraft_snow_water_mixing_ratio'                      , 'units':'1'}         ,
  'b_up_dconv'      : {'standard_name':'deep_convective_updraft_buoyancy'                                     , 'units':'m s-2'}     ,
  'ent_up_dconv'    : {'standard_name':'deep_convective_entrainment'                                          , 'units':'m-1'}       ,
  'det_up_dconv'    : {'standard_name':'deep_convective_detrainment'                                          , 'units':'m-1'}       ,

# 11. Wake parameterization variables
  'delta_ta'         : {'standard_name':'air_temperature_difference_between_wake_and_offwake_regions'                                  , 'units':'K'}     ,
  'delta_theta'      : {'standard_name':'potential_temperature_difference_between_wake_and_offwake_regions'                            , 'units':'K'}     ,
  'delta_qv'         : {'standard_name':'specific_humidity_difference_between_wake_and_offwake_regions'                                , 'units':'1'}     ,
  'sigmaw'           : {'standard_name':'wake_fractional_area'                                                                         , 'units':'1'}     ,
  'hw'               : {'standard_name':'wake_depth'                                                                                   , 'units':'m'}     ,
  'wdens'            : {'standard_name':'wake_density'                                                                                 , 'units':'m-2'}   ,
  'cstar'            : {'standard_name':'wake_spreading_velocity'                                                                      , 'units':'m s-1'} ,
  'wake_pe'          : {'standard_name':'wake_potential_energy'                                                                        , 'units':'J kg-1'},
  'wake_alp'         : {'standard_name':'wake_available_lifting_power'                                                                 , 'units':'W m-2'} ,
  'wake_wap'         : {'standard_name':'wake_vertical_velocity'                                                                       , 'units':'Pa s-1'},
  'delta_tnta_dconv' : {'standard_name':'differential_tendency_of_air_temperature_between_wake_and_offwake_regions_due_to_convection'  , 'units':'K s-1'} ,
  'delta_tnqv_dconv' : {'standard_name':'differential_tendency_of_specific_humidity_between_wake_and_offwake_regions_due_to_convection', 'units':'s-1'}   ,
  'delta_tnta_turb'  : {'standard_name':'differential_tendency_of_air_temperature_between_wake_and_offwake_regions_due_to_turbulence'  , 'units':'K s-1'} ,
  'delta_tnqv_turb'  : {'standard_name':'differential_tendency_of_specific_humidity_between_wake_and_offwake_regions_due_to_turbulence', 'units':'s-1'}   ,

# 12. Radiative flux variables
  'rld'    : {'standard_name':'downwelling_longwave_flux_in_air'                      , 'units':'W m-2'},
  'rlu'    : {'standard_name':'upwelling_longwave_flux_in_air'                        , 'units':'W m-2'},
  'rsd'    : {'standard_name':'downwelling_shortwave_flux_in_air'                     , 'units':'W m-2'},
  'rsu'    : {'standard_name':'upwelling_shortwave_flux_in_air'                       , 'units':'W m-2'},
  'rldcs'  : {'standard_name':'downwelling_longwave_flux_in_air_assuming_clear_sky'   , 'units':'W m-2'},
  'rlucs'  : {'standard_name':'upwelling_longwave_flux_in_air_assuming_clear_sky'     , 'units':'W m-2'},
  'rsdcs'  : {'standard_name':'downwelling_shortwave_flux_in_air_assuming_clear_sky'  , 'units':'W m-2'},
  'rsucs'  : {'standard_name':'upwelling_shortwave_flux_in_air_assuming_clear_sky'    , 'units':'W m-2'},
  'rsdt'   : {'standard_name':'toa_incoming_shortwave_flux'                           , 'units':'W m-2'},
  'rsut'   : {'standard_name':'toa_outgoing_shortwave_flux'                           , 'units':'W m-2'},
  'rlut'   : {'standard_name':'toa_outgoing_longwave_flux'                            , 'units':'W m-2'},
  'rsutcs' : {'standard_name':'toa_outgoing_shortwave_flux_assuming_clear_sky'        , 'units':'W m-2'},
  'rlutcs' : {'standard_name':'toa_outgoing_longwave_flux_assuming_clear_sky'         , 'units':'W m-2'},
  'rlds'   : {'standard_name':'surface_downwelling_longwave_flux'                     , 'units':'W m-2'},
  'rlus'   : {'standard_name':'surface_upwelling_longwave_flux'                       , 'units':'W m-2'},
  'rsds'   : {'standard_name':'surface_downwelling_shortwave_flux'                    , 'units':'W m-2'},
  'rsus'   : {'standard_name':'surface_upwelling_shortwave_flux'                      , 'units':'W m-2'},
  'rldscs' : {'standard_name':'surface_downwelling_longwave_flux_assuming_clear_sky'  , 'units':'W m-2'},
  'rluscs' : {'standard_name':'surface_upwelling_longwave_flux_assuming_clear_sky'    , 'units':'W m-2'},
  'rsdscs' : {'standard_name':'surface_downwelling_shortwave_flux_assuming_clear_sky' , 'units':'W m-2'},
  'rsuscs' : {'standard_name':'surface_upwelling_shortwave_flux_assuming_clear_sky'   , 'units':'W m-2'},

# 13. Misc
  'wstar' : {'standard_name':'free convection velocity scale'   , 'units':'m s-1'},
}
